### ISSUE TITLE
Remove `filter_` from `split_pilot_set`

### ISSUE THREAD

**Issue by raikens1** [raikens1/BigMatch#99]
Throws a warning every time it's called.

**Comment by JonathanChiang** [comment]
best to cite where the script where the warning comes from. Will save future you time

**Comment by raikens1** [comment]
Oooh fancy...

**Comment by raikens1** [comment]
Fixed this by renaming the column in the data.frame.  Probably a better-practice way to do this with quo() enquo()a la [dplyr vignette](https://cran.r-project.org/web/packages/dplyr/vignettes/programming.html) but it seems like a headache.  Moving this to the back-burner for now.
